/**
Name : NodeJS Custom CLI Module - Project Generator Template
Author:  Dilusha Gonagala
License : MIT
Version : 1.0
**/

//Module Dependencies
var fs = require('fs-extra');
var child_process = require('child_process');
var path = require("path");
var packages = require("./packages");

module.exports = {

  generate: function(projecttype, projectname) {


    if (!projecttype == undefined || !projecttype == "" && !projectname == undefined || !projectname == "") {

      //AngularSimple Generator
      if (projecttype == "angularsimple") {

        //Create directory with the user's given project name on the current cli path
        fs.mkdirs('./' + projectname + '', function(err) {
          if (err) {
            // console.error(err);
          } else {

            fs.writeFile("./" + projectname + "/README.MD", "Generated By GenSimple", function(err) {
              if (err) {
                // console.log(err);
              }
              // We now know that evrything is smooth
              else {
                //  console.log(__dirname);
                //  console.log(__filename);
                var dirname = path.resolve(__dirname);
                // console.log(path.resolve(__dirname))

                var dirstr = dirname.substr(dirname.lastIndexOf('/') + 1) + '$',
                  fixedurl = dirname.replace(new RegExp(dirstr), '');

                fs.copy(fixedurl + '/templates/angularsimple/', "./" + projectname + "", function(err) {
                  if (err) {
                    console.error(err)
                  } else {


                    var currentDir = process.cwd(), totdalPackageCount =packages.angularsimple.packages.length,
                    installedPackageCount=0 ;


                    for (var i = 0; i < packages.angularsimple.packages.length; i++) {


                      var packagenpm = packages.angularsimple.packages[i];
                      console.log("Installing Dependency..." + packagenpm);
                      child_process.exec(["npm install --prefix ./" + projectname + " " + packagenpm + ""], function(err, out, code) {
                        if (err instanceof Error) {
                          throw err;
                        } else {
                          installedPackageCount ++;
                          if(totdalPackageCount == installedPackageCount){

                            console.log("Success ! Your AngularSimple App Is up And Running on http://localhost:5000");
                            child_process.exec(["node ./" + projectname + "/server.js"], function(err, out, code) {
                              if (err instanceof Error) {
                                console.log(err);
                                throw err;
                              }

                            });
                          }
                        }

                      });



                    }


                  }

                });

              }

            });

          }

        });


      }

    }



  }


}
